site_name: GDKI - Projekt

theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  name: material
  logo: images/myCargonautLogo.png

nav:
  - Home:
      - "index.md"
  - Ki:
      - "ki/index.md"
  - App:
      - "app/konzept.md"
      - "app/installation.md"

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - attr_list
  - admonition
  - pymdownx.details

dev_addr: "127.0.0.1:8001"

plugins:
  - search
  - pdf-export:
      combined: true
      enabled_if_env: PDF_EXPORT
