item {
    id: 0
    name: 'zwanzig'
}

item {
    id: 1
    name: 'dreissig'
}

item {
    id: 2
    name: 'fuenfzig'
}

item {
    id: 3
    name: 'sechzig'
}
item {
    id: 4
    name: 'siebzig'
}

item {
    id: 5
    name: 'achtzig'
}
item {
    id: 6
    name: 'neunzig'
}
item {
    id: 7
    name: 'hundert'
}
item {
    id: 8
    name: 'hundertzehn'
}
item {
    id: 9
    name: 'hundertzwanzig'
}
item {
    id: 10
    name: 'hundertdreissig'
}
item {
    id: 11
    name: 'zwanzigEnde'
}
item {
    id: 12
    name: 'dreissigEnde'
}
item {
    id: 13
    name: 'fünfzigEnde'
}
item {
    id: 14
    name: 'sechzigEnde'
}
item {
    id: 15
    name: 'siebzigEnde'
}
item {
    id: 16
    name: 'achtzigEnde'
}
item {
    id: 17
    name: 'neunzigEnde'
}
item {
    id: 18
    name: 'hundertEnde'
}
item {
    id: 19
    name: 'hundertzehnEnde'
}
item {
    id: 20
    name: 'hundertzwanzigEnde'
}
item {
    id: 21
    name: 'hundertdreissigEnde'
}
item {
    id: 22
    name: 'ende'
}
item {
    id: 23
    name: 'spielstrasse'
}
item {
    id: 24
    name: 'spielstrasseEnde'
}
item {
    id: 25
    name: 'ort'
}
item {
    id: 26
    name: 'ortAusgang'
}
item {
    id: 27
    name: 'ortEnde'
}
item {
    id: 28
    name: 'autobahn'
}
item {
    id: 29
    name: 'autobahnEnde'
}
item {
    id: 30
    name: 'zoneZwanzig'
}
item {
    id: 31
    name: 'zoneDreissig'
}
item {
    id: 32
    name: 'zoneZwanzigEnde'
}
item {
    id: 33
    name: 'zoneDreissigEnde'
}










